CREATE TABLE KHACHHANG (
    MAKHACHHANG VARCHAR(255) PRIMARY KEY,
    TENKHACHHANG VARCHAR(255),
    DIACHI VARCHAR(255),
    EMAIL VARCHAR(255),
    DIENTHOAI VARCHAR(20)
);

CREATE TABLE DONDATHANG (
    SOHOADON INT PRIMARY KEY,
    MAKHACHHANG VARCHAR(255),
    MANHANVIEN VARCHAR(255),
    NGAYDATHANG DATE,
	NGAYCHUYENHANG DATE,
	NOIGIAOHANG VARCHAR(255),
    CONSTRAINT fk_ddh_kh FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG),
    CONSTRAINT fk_ddh_nv FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
);

CREATE TABLE NHANVIEN (
    MANHANVIEN VARCHAR(255) PRIMARY KEY,
    HO VARCHAR(255),
    TEN VARCHAR(255),
    NGAYSINH DATE,
	NGAYLAMVIEC DATE,
    DIACHI VARCHAR(255),
    DIENTHOAI VARCHAR(20),
    LUONGCOBAN DECIMAL(18, 2)
);

CREATE TABLE NHACUNGCAP (
    MACONGTY VARCHAR(255) PRIMARY KEY,
    TENCONGTY NVARCHAR(255),
    DIACHI NVARCHAR(255),
    DIENTHOAI VARCHAR(20),
    EMAIL VARCHAR(255)
);

CREATE TABLE MATHANG (
    MAHANG INT PRIMARY KEY,
    TENHANG NVARCHAR(255),
	MACONGTY VARCHAR(255),
	MALOAIHANG VARCHAR(255),
	SOLUONG VARCHAR(255),
	DONVITINH VARCHAR(255),
    GIAHANG DECIMAL(18, 2),
    CONSTRAINT fk_mt_ncc FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY),
    CONSTRAINT fk_mt_lh FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAI)
);

CREATE TABLE LOAIHANG (
    MALOAI INT PRIMARY KEY,
    TENLOAI VARCHAR(255)
);
CREATE TABLE CHITIETDATHANG (
	SOHOADON INT,
	MAHANG INT,
	PRIMARY KEY (SOHOADON, MAHANG),
	GIABAN DECIMAL(18, 2),
	SOLUONG VARCHAR(255),
	MUCGIAMGIA VARCHAR(255),
	CONSTRAINT fk_ctdh_mt FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG),
	CONSTRAINT fk_ctdh_ddh FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON),
);